package dev.vxrp.util.launch.enums

enum class LaunchOptionSectionType {
    HELP_COMMAND,
    TEMPLATE_COMMAND,
    VERIFY_COMMAND,
    NOTICE_OF_DEPARTURE_COMMAND,
    REGULARS_COMMAND,
    PLAYER_COMMAND,
    SETTINGS_COMMAND,
    APPLICATION_COMMAND,

    STATUS_COMMAND,
    STATUS_PLAYERLIST_COMMAND,
    STATUS_TEMPLATE_COMMAND,

    HELP_BUTTONS,
    TICKET_BUTTONS,
    APPLICATION_BUTTONS,
    VERIFY_BUTTONS,
    NOTICE_OF_DEPARTURE_BUTTONS,
    REGULARS_BUTTONS,
    TICKET_ENTITY_SELECT_MENUS,
    TICKET_MODALS,
    APPLICATION_MODALS,
    NOTICE_OF_DEPARTURE_MODALS,
    TICKET_STRING_SELECT_MENUS,
    APPLICATION_STRING_SELECT_MENUS
}