package dev.vxrp.util.launch.enums

enum class LaunchOptionType {
    BOT,
    STATUS_CLUSTER,
    COMMAND_MANAGER,
    COMMAND_LISTENER,
    STATUS_COMMAND_LISTENER,
    BUTTON_LISTENER,
    ENTITY_SELECT_LISTENER,
    MODAL_LISTENER,
    STRING_SELECT_LISTENER,
    NOTICE_OF_DEPARTURE_CHECKER,
    REGULARS_CHECKER
}